if(NOT DEFINED VCPKG_ROOT)
    if(DEFINED ENV{VCPKG_ROOT})
        set(VCPKG_ROOT $ENV{VCPKG_ROOT})
    else()
        set(VCPKG_ROOT "C:/source/vcpkg")
    endif()
endif()

if(NOT DEFINED QT_ROOT)
    if(DEFINED ENV{QT_ROOT})
        set(QT_ROOT $ENV{QT_ROOT})
    else()
        set(QT_ROOT "C:/Qt6.8.3/6.8.3/msvc2022_64")
    endif()
endif()

if(NOT DEFINED VK_SDK_ROOT)
    if(DEFINED ENV{VK_SDK_ROOT})
        set(VK_SDK_ROOT $ENV{VK_SDK_ROOT})
    else()
        set(VK_SDK_ROOT "C:/VulkanSDK/1.3.290.0")
    endif()
endif()
