if(NOT DEFINED VCPKG_ROOT OR VCPKG_ROOT STREQUAL "")
    if(DEFINED ENV{VCPKG_ROOT} AND NOT "$ENV{VCPKG_ROOT}" STREQUAL "")
        set(VCPKG_ROOT "$ENV{VCPKG_ROOT}")
    else()
        set(VCPKG_ROOT C:/source/vcpkg)
    endif()
endif()

if(NOT DEFINED QT_ROOT OR QT_ROOT STREQUAL "")
    if(DEFINED ENV{QT_ROOT} AND NOT "$ENV{QT_ROOT}" STREQUAL "")
        set(QT_ROOT "$ENV{QT_ROOT}")
    else()
        set(QT_ROOT C:/Qt/6.6.3/msvc2022_64)
    endif()
endif()

#set(VK_SDK C:/VulkanSDK/1.3.275.0/Include)
set(VK_SDK_ROOT C:/VulkanSDK/1.3.290.0)
